/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.face;

import com.bosco.CAs_Records;
import com.bosco.CAs_RecordsDAO;
import com.bosco.Courses;
import com.bosco.CoursesDAO;
import com.bosco.Department;
import com.bosco.DepartmentDAO;
import com.bosco.ICAs_Records;
import com.bosco.ICourses;
import com.bosco.IDepartment;
import com.table.*;

/**
 *
 * @author charles
 */
public class MasterPageGUI extends javax.swing.JFrame {

    /**
     * Creates new form MasterPageGUI
     */
      ICAs_Records create = new CAs_RecordsDAO();
    CAs_Records get = new CAs_Records();
    ICourses create1 = new CoursesDAO();
    Courses get1 = new Courses();
    IDepartment create2 = new DepartmentDAO();
     Department get2 = new Department();
    public MasterPageGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Regtstudent = new javax.swing.JToggleButton();
        StaffReg = new javax.swing.JToggleButton();
        departmentReg = new javax.swing.JToggleButton();
        courseReg = new javax.swing.JToggleButton();
        paymentreg = new javax.swing.JToggleButton();
        recordreg = new javax.swing.JToggleButton();
        termsect = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        Regtstudent1 = new javax.swing.JToggleButton();
        StaffReg1 = new javax.swing.JToggleButton();
        departmentReg1 = new javax.swing.JToggleButton();
        courseReg1 = new javax.swing.JToggleButton();
        paymentreg1 = new javax.swing.JToggleButton();
        recordreg1 = new javax.swing.JToggleButton();
        termsect1 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        closeapp = new javax.swing.JMenu();
        Returnback = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Regtstudent.setText("Register Student");
        Regtstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegtstudentActionPerformed(evt);
            }
        });

        StaffReg.setText("Register Staff");
        StaffReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffRegActionPerformed(evt);
            }
        });

        departmentReg.setText("Register Department");
        departmentReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentRegActionPerformed(evt);
            }
        });

        courseReg.setText("Register Courses");
        courseReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseRegActionPerformed(evt);
            }
        });

        paymentreg.setText("Make Payment");
        paymentreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentregActionPerformed(evt);
            }
        });

        recordreg.setText("Record CAs");
        recordreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordregActionPerformed(evt);
            }
        });

        termsect.setText("Register TermSection");
        termsect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termsectActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Regtstudent1.setText("View Student");
        Regtstudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regtstudent1ActionPerformed(evt);
            }
        });

        StaffReg1.setText("View Staff");
        StaffReg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffReg1ActionPerformed(evt);
            }
        });

        departmentReg1.setText("View Department");
        departmentReg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentReg1ActionPerformed(evt);
            }
        });

        courseReg1.setText("View Courses");
        courseReg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseReg1ActionPerformed(evt);
            }
        });

        paymentreg1.setText("View paid payment");
        paymentreg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentreg1ActionPerformed(evt);
            }
        });

        recordreg1.setText("View Recorded CAs");
        recordreg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordreg1ActionPerformed(evt);
            }
        });

        termsect1.setText("View TermSection");
        termsect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termsect1ActionPerformed(evt);
            }
        });

        closeapp.setText("Close app");
        closeapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeappMouseClicked(evt);
            }
        });
        jMenuBar1.add(closeapp);

        Returnback.setText("Back");
        Returnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnbackMouseClicked(evt);
            }
        });
        jMenuBar1.add(Returnback);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StaffReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Regtstudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(departmentReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paymentreg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recordreg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(termsect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courseReg, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StaffReg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Regtstudent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(departmentReg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paymentreg1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recordreg1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(termsect1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courseReg1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(Regtstudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StaffReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(departmentReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courseReg)
                        .addGap(18, 18, 18)
                        .addComponent(paymentreg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(recordreg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(termsect))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(Regtstudent1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StaffReg1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(departmentReg1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courseReg1)
                        .addGap(18, 18, 18)
                        .addComponent(paymentreg1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(recordreg1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(termsect1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnbackMouseClicked
        LoginGUI.main(new String[] {});
    }//GEN-LAST:event_ReturnbackMouseClicked

    private void closeappMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeappMouseClicked
        LoginGUI tt = new LoginGUI();
        tt.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_closeappMouseClicked

    private void StaffReg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffReg1ActionPerformed
        StaffViewGui.main(new String[] {});
    }//GEN-LAST:event_StaffReg1ActionPerformed

    private void RegtstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegtstudentActionPerformed
        StudentGUI.main(new String[] {});
    }//GEN-LAST:event_RegtstudentActionPerformed

    private void departmentRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentRegActionPerformed
        DepartmentGUI.main(new String[] {});
    }//GEN-LAST:event_departmentRegActionPerformed

    private void courseRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseRegActionPerformed
        CoursesGUI.main(new String[] {});
    }//GEN-LAST:event_courseRegActionPerformed

    private void paymentregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentregActionPerformed
        PaymentGUI.main(new String[] {});
    }//GEN-LAST:event_paymentregActionPerformed

    private void recordregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordregActionPerformed
       CAs_RecordsGUI.main(new String[] {});
    }//GEN-LAST:event_recordregActionPerformed

    private void termsectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termsectActionPerformed
        TermSectionGUI.main(new String[] {});
    }//GEN-LAST:event_termsectActionPerformed

    private void Regtstudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regtstudent1ActionPerformed
        StudentViewGui.main(new String[] {});
    }//GEN-LAST:event_Regtstudent1ActionPerformed

    private void departmentReg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentReg1ActionPerformed
        DepartmentViewGui.main(new String[] {});
    }//GEN-LAST:event_departmentReg1ActionPerformed

    private void courseReg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseReg1ActionPerformed
        CourseViewGui.main(new String[] {});
    }//GEN-LAST:event_courseReg1ActionPerformed

    private void paymentreg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentreg1ActionPerformed
        PaymentViewGui.main(new String[] {});
    }//GEN-LAST:event_paymentreg1ActionPerformed

    private void recordreg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordreg1ActionPerformed
        RecordcasViewGui.main(new String[] {});
    }//GEN-LAST:event_recordreg1ActionPerformed

    private void termsect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termsect1ActionPerformed
        TermsectionViewGui.main(new String[] {});
                
    }//GEN-LAST:event_termsect1ActionPerformed

    private void StaffRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffRegActionPerformed
        StaffGUI.main(new String[] {});
    }//GEN-LAST:event_StaffRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterPageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Regtstudent;
    private javax.swing.JToggleButton Regtstudent1;
    private javax.swing.JMenu Returnback;
    private javax.swing.JToggleButton StaffReg;
    private javax.swing.JToggleButton StaffReg1;
    private javax.swing.JMenu closeapp;
    private javax.swing.JToggleButton courseReg;
    private javax.swing.JToggleButton courseReg1;
    private javax.swing.JToggleButton departmentReg;
    private javax.swing.JToggleButton departmentReg1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton paymentreg;
    private javax.swing.JToggleButton paymentreg1;
    private javax.swing.JToggleButton recordreg;
    private javax.swing.JToggleButton recordreg1;
    private javax.swing.JToggleButton termsect;
    private javax.swing.JToggleButton termsect1;
    // End of variables declaration//GEN-END:variables
}
